force-app/main/default/objects/Indeed_com_AppForm__c/Indeed_com_AppForm__c.object-meta.xml
<CustomObject>
    <description>Persons will fill the data in these forms.</description>
    <label>Indeed.com AppForm</label>
    <nameField>
        <label>Indeed.com AppForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indeed.com AppForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indeed_com_AppForm__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <description>Reference: Mail dated 01/01/2020 from client Larey.
or
Task Number: 24243</description>
    <inlineHelpText>Please enter the number of years you worked for.
Example: 3.10</inlineHelpText>
    <label>Experience</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Indeed_com_AppForm__c/fields/Salary_Expected__c.field-meta.xml
<CustomField>
    <fullName>Salary_Expected__c</fullName>
    <description>Reference: Mail dated 01/01/2020 from client Larey.
or
Task Number: 24243</description>
    <inlineHelpText>Please enter the salary you are expecting from the company.
Example; 1500000</inlineHelpText>
    <label>Salary Expected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CheckTriggerClass.cls
Public Class CheckTriggerClass
{
   Public Static void BeforeInsertFn(list<Indeed_com_AppForm__c> abcd)
   {
      for (Indeed_com_AppForm__c i: abcd)
      {
       //if (i.Experience__c > 10)
          i.Salary_Expected__c = i.Salary_Expected__c - 2000;
      }
   }
   Public Static void BeforeUpdateFn(list<Indeed_com_AppForm__c> abcd)
   {
      for (Indeed_com_AppForm__c i: abcd){
     //  if (i.Experience__c > 10)
          i.Salary_Expected__c = i.Salary_Expected__c -2000;
      }
   }
}