force-app/main/default/objects/Indeed_com_AppForm__c/Indeed_com_AppForm__c.object-meta.xml
<CustomObject>
    <description>Persons will fill the data in these forms.</description>
    <label>Indeed.com AppForm</label>
    <nameField>
        <label>Indeed.com AppForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indeed.com AppForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indeed_com_AppForm__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <description>Reference: Mail dated 01/01/2020 from client Larey.
or
Task Number: 24243</description>
    <inlineHelpText>Please enter the number of years you worked for.
Example: 3.10</inlineHelpText>
    <label>Experience</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Indeed_com_AppForm__c/fields/Salary_Expected__c.field-meta.xml
<CustomField>
    <fullName>Salary_Expected__c</fullName>
    <description>Reference: Mail dated 01/01/2020 from client Larey.
or
Task Number: 24243</description>
    <inlineHelpText>Please enter the salary you are expecting from the company.
Example; 1500000</inlineHelpText>
    <label>Salary Expected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestApexClass.cls
public class TestApexClass {
    
    Public Static Void TestFunction1(List<Indeed_com_AppForm__c> IndeedRecords){
        
        For(Indeed_com_AppForm__c a: IndeedRecords)//Indeed_com_AppForm__c a = New Indeed_com_AppForm__c (); a = Trigger.New[0]
       {
        if (a.Experience__c == 5)
            a.Salary_Expected__c = 123456789;
            system.debug('a.Salary_Expected__c: '+a.Salary_Expected__c);
        }  
    }
    
    Public Static Void TestFunction2(){
       Mobile__c b = new Mobile__c();
       b= [select Id, brand__c FROM Mobile__c where Brand__c = 'Samsung' LIMIT 1];
       b.Brand__c = 'Apple';
        Update b;
    }

}