force-app/main/default/objects/Indeed_com_AppForm__c/Indeed_com_AppForm__c.object-meta.xml
<CustomObject>
    <description>Persons will fill the data in these forms.</description>
    <label>Indeed.com AppForm</label>
    <nameField>
        <label>Indeed.com AppForm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indeed.com AppForms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Indeed_com_AppForm__c/fields/Experience__c.field-meta.xml
<CustomField>
    <fullName>Experience__c</fullName>
    <description>Reference: Mail dated 01/01/2020 from client Larey.
or
Task Number: 24243</description>
    <inlineHelpText>Please enter the number of years you worked for.
Example: 3.10</inlineHelpText>
    <label>Experience</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestFutureAnnotationApex.cls
public class TestFutureAnnotationApex {
    
    Public static void Function1(List<Indeed_com_AppForm__c> List1){
        
        For(Indeed_com_AppForm__c Record1 : List1){
            if (Record1.Experience__c == 15){
                Record1.Experience__c = 3;
            }
           update Record1;
        }
    }
/*	

        List<Indeed_com_AppForm__c> List2 = New List<Indeed_com_AppForm__c> ();
        
        
        For(Indeed_com_AppForm__c Record1 : List1){
			if (Record1.Experience__c == 15){
                Record1.Experience__c = 3;   
            }   
                List2.add(Record1);
           //update Record1;
        }
        update List2;

*/

 /*
    @Future
    Public static void Function2(List<Indeed_com_AppForm__c> List1){
        
        For(Indeed_com_AppForm__c Record1 : List1){
            if (Record1.Experience__c == 3){
                Record1.Experience__c = 15;
            }
            insert Record1;
        }
    }
*/   
}