force-app/main/default/objects/Mobile__c/Mobile__c.object-meta.xml
<CustomObject>
    <label>Mobile</label>
    <nameField>
        <label>Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mobiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile__c/fields/Discount_Status__c.field-meta.xml
<CustomField>
    <fullName>Discount_Status__c</fullName>
    <label>Discount Status</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Assignment2Class.cls
public class Assignment2Class {
    
    Public static void Assignment2FunctionBeforeInsert (List<Mobile__c> MobileRecords){
        for (Mobile__c j: MobileRecords){
            if (j.Brand__c == 'Samsung'){
                j.Price__c = j.Price__c * 0.9;
                j.Discount_Status__c = 'Congrats...! You got 10% Discount';
            }
            else if (j.Brand__c == 'Apple'){
                j.Price__c = j.Price__c * 0.8;
            	j.Discount_Status__c = 'Congrats...! You got 20% Discount';
            }
        }		 
    }

        Public static void Assignment2FunctionBeforeUpdate (List<Mobile__c> MobileRecords){
        for (Mobile__c j: MobileRecords){
            if (j.Brand__c == 'Samsung'){
                j.Price__c = j.Price__c * 0.95;
                j.Discount_Status__c = 'Congrats...! You got 5% Discount';
            }
            else if (j.Brand__c == 'Apple'){
                j.Discount_Status__c = 'Sorry...! You got 0% Discount because you requested discount after purchasing..!';
            } 
        }		
    }
}