force-app/main/default/objects/Candidate_Detail__c/Candidate_Detail__c.object-meta.xml
<CustomObject>
    <label>Candidate Detail</label>
    <nameField>
        <label>Candidate Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidate Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate_Detail__c/fields/Are_you_ready_to_attend_on_weekends__c.field-meta.xml
<CustomField>
    <fullName>Are_you_ready_to_attend_on_weekends__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Are you ready to attend on weekends...?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Education_Detail__c/Education_Detail__c.object-meta.xml
<CustomObject>
    <label>Education Detail</label>
    <nameField>
        <label>Education Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Detail__c/fields/Candidate_Detail__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Detail__c</fullName>
    <label>Candidate Detail</label>
    <referenceTo>Candidate_Detail__c</referenceTo>
    <relationshipLabel>Education Details</relationshipLabel>
    <relationshipName>Education_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/addCandidateDetails.cls
public class addCandidateDetails{
    
    @AuraEnabled
    public static id insertCandidateDetails(Candidate_Detail__c temp){
        //public static void insertCandidateDetails(string temp){
        
        system.debug('temp: '+ temp);
        //temp.Are_you_ready_to_attend_on_weekends__c = true;
        insert temp;
        return temp.id;
    }
    
    @AuraEnabled
    public static id insertEducationDetails(Education_Detail__c temp1){
        //public static void insertCandidateDetails(string temp){
        
        system.debug('temp: '+ temp1);
        //temp.Are_you_ready_to_attend_on_weekends__c = true;
        try{
            insert temp1;
        }catch(exception e){
            system.debug('exception is: '+ e);
        }
        	
        return temp1.id;
    }
}